# Generated by Django 5.1 on 2024-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('sub_category', models.CharField(max_length=250, verbose_name='Подкатегория')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('date', models.DateField(verbose_name='Дата добаления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
