# Generated by Django 5.1 on 2024-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('sub_category', models.CharField(max_length=250, verbose_name='Подкатегория')),
                ('full_text', models.TextField(verbose_name='Основной текст')),
                ('date', models.DateField(verbose_name='Дата добаления')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
